# Generated by Django 3.2.4 on 2021-06-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('servers', models.ManyToManyField(related_name='group_servers', to='main_app.Server')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
