# Generated by Django 3.2.4 on 2021-06-26 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_upgraderesult'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpgradeResultDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(default='', max_length=255)),
                ('package', models.CharField(default='', max_length=255)),
                ('uuid', models.CharField(max_length=50)),
                ('pid', models.CharField(max_length=50)),
                ('event', models.CharField(max_length=50)),
                ('host', models.CharField(max_length=50)),
                ('last_version', models.CharField(blank=True, max_length=250, null=True)),
                ('upgraded_version', models.CharField(blank=True, max_length=250, null=True)),
                ('state', models.CharField(max_length=50)),
                ('changed', models.BooleanField(blank=True, null=True)),
                ('msg', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=150, null=True)),
                ('resp_dump', models.TextField(blank=True, null=True)),
                ('runner_result', models.CharField(default='Unknown', max_length=120)),
                ('upgrade_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.upgraderesult')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
